# **Aashray - Week 2 Data science bootcamp**

**Numpy Questions**

Q1

In [3]:
import numpy as np

A = np.array([[1, 2, 7], [4, 9, 11]])
B = np.array([[5, 3, 9], [10, 11, 12]])

vertical_stack = np.vstack((A, B))

horizontal_stack = np.hstack((A, B))

print("Array A:\n", A)
print("\nArray B:\n", B)
print("\nVertically Stacked Array:\n", vertical_stack)
print("\nHorizontally Stacked Array:\n", horizontal_stack)


Array A:
 [[ 1  2  7]
 [ 4  9 11]]

Array B:
 [[ 5  3  9]
 [10 11 12]]

Vertically Stacked Array:
 [[ 1  2  7]
 [ 4  9 11]
 [ 5  3  9]
 [10 11 12]]

Horizontally Stacked Array:
 [[ 1  2  7  5  3  9]
 [ 4  9 11 10 11 12]]


Q2

In [4]:

common_elements = np.intersect1d(A, B)

print("Array A:\n", A)
print("\nArray B:\n", B)
print("\nCommon elements between A and B:\n", common_elements)

Array A:
 [[ 1  2  7]
 [ 4  9 11]]

Array B:
 [[ 5  3  9]
 [10 11 12]]

Common elements between A and B:
 [ 9 11]


Q3

In [5]:

# Specify the range
lower_bound = 5
upper_bound = 10

# Extract elements within the specified range using a boolean mask
elements_in_range = A[(A >= lower_bound) & (A <= upper_bound)]

print("Array A:\n", A)
print(f"\nElements in A between {lower_bound} and {upper_bound}:\n", elements_in_range)


Array A:
 [[ 1  2  7]
 [ 4  9 11]]

Elements in A between 5 and 10:
 [7 9]


Q4

In [6]:

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

filtered_rows = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]

print("Filtered rows where petallength > 1.5 and sepallength < 5.0:\n", filtered_rows)


Filtered rows where petallength > 1.5 and sepallength < 5.0:
 [[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


**Pandas Questions**

Q5

In [7]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Select every 20th row starting from the first row (index 0)
filtered_df = df.iloc[::20, :][['Manufacturer', 'Model', 'Type']]

print("Filtered rows for every 20th entry (Manufacturer, Model, Type):\n", filtered_df)


Filtered rows for every 20th entry (Manufacturer, Model, Type):
    Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


Q6

In [8]:
min_price_mean = df['Min.Price'].mean()
max_price_mean = df['Max.Price'].mean()

df['Min.Price'].fillna(min_price_mean, inplace=True)
df['Max.Price'].fillna(max_price_mean, inplace=True)

print("Updated DataFrame with missing values in Min.Price and Max.Price replaced by mean:\n", df[['Min.Price', 'Max.Price']].head())

Updated DataFrame with missing values in Min.Price and Max.Price replaced by mean:
    Min.Price  Max.Price
0  12.900000  18.800000
1  29.200000  38.700000
2  25.900000  32.300000
3  17.118605  44.600000
4  17.118605  21.459091


<ipython-input-8-232817aa6b67>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Min.Price'].fillna(min_price_mean, inplace=True)
<ipython-input-8-232817aa6b67>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try us

Q7

In [9]:
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
print(df)
row_sum_gt_100 = df[df.sum(axis=1) > 100]
print(row_sum_gt_100)

     0   1   2   3
0   17  25  15  30
1   38  39  22  20
2   32  35  25  38
3   15  23  36  34
4   21  28  28  37
5   18  37  22  23
6   16  18  18  31
7   25  32  32  29
8   24  16  29  20
9   16  21  30  35
10  38  39  22  37
11  33  20  34  37
12  27  10  12  28
13  21  36  23  10
14  34  11  11  39
     0   1   2   3
1   38  39  22  20
2   32  35  25  38
3   15  23  36  34
4   21  28  28  37
7   25  32  32  29
9   16  21  30  35
10  38  39  22  37
11  33  20  34  37
